### PR TITLE
Add implementations link.

### PR DESCRIPTION
**Pull request by hadrielk**
Also fix typo in NRB section.

### CODE REVIEW

**Comment by hadrielk** [comment]
closes #29

**Comment by guyharris** [comment]
I've added a pile of comments.

**Comment by hadrielk** [comment]
Do you want the changes for those comments in this pull change, or can you accept this one, and I'll create another for the changes?

**Comment by guyharris** [comment]
> Do you want the changes for those comments in this pull change, or can you accept this one, and I'll create another for the changes?

I'd say the typo fixes, such as "inidicated" -> "indicated", should be added to this pull change.  The suggested wordsmithing could go into another change.

**Comment by hadrielk** [comment]
Updated with typos being fixed.

**Comment by packetfoo** [comment]
Maybe I read the diff wrong, but isn't "flags" now misspelled as "falgs"? :-)

**Comment by hadrielk** [comment]
Bleh. Google docs would be a lot easier than this process. :smirk_cat:

**Pull request merged**
