### PR TITLE
Upgrade Makefile

### PR DESCRIPTION
**Pull request by mcr**
This upgrades the Makefile to the latest template from Martin Thomson.

### CODE REVIEW

**Comment by alagoutte** [comment]
Look good (may be also convert after to Markdown ?)

**Comment by mcr** [comment]
Yes, I would like to convert to markdown if I have everyone's blessing.

**Comment by guyharris** [comment]
> Yes, I would like to convert to markdown if I have everyone's blessing.

Using something such as [mmark](https://github.com/mmarkdown/mmark) to convert from Markdown to xml2rfc?

**Comment by guyharris** [comment]
> This upgrades the Makefile to the latest template from Martin Thomson.

So that's [Martin Thomson](https://datatracker.ietf.org/person/Martin%20Thomson) of the [Tools Architecture and Strategy Team (tools-arch)](https://datatracker.ietf.org/group/tools-arch/about/), presumably.

Are these from the https://github.com/martinthomson/i-d-template repository?

**Comment by mcr** [comment]
> > Yes, I would like to convert to markdown if I have everyone's blessing.
> 
> Using something such as [mmark](https://github.com/mmarkdown/mmark) to convert from Markdown to xml2rfc?

I would use kramdown. https://github.com/cabo/kramdown-rfc2629  you can see many IDs that I edit in my github repo, and also at ietf-homenet-wg or ietf-roll-wg or anima-wg.

**Comment by guyharris** [comment]
> > > Yes, I would like to convert to markdown if I have everyone's blessing.
> > 
> > 
> > Using something such as [mmark](https://github.com/mmarkdown/mmark) to convert from Markdown to xml2rfc?
> 
> I would use kramdown. https://github.com/cabo/kramdown-rfc2629 you can see many IDs that I edit in my github repo, and also at ietf-homenet-wg or ietf-roll-wg or anima-wg.

kramdown itself being at https://kramdown.gettalong.org.

**Comment by guyharris** [comment]
So having the checked-in version be Markdown would mean that the home page could just link to the copy of the Markdown version in the repository and GitHub would automatically format it into a Web page with its Markdown renderer, and kramdown + pick-your-xml2rfc-to-XXX-converter would be used to produce text/standard-html-version-of-an-RFC/PDF/whatever?

**Comment by mcr** [comment]
> So having the checked-in version be Markdown would mean that the home page could just link to the copy of the Markdown version in the repository and GitHub would automatically format it into a Web page with its Markdown renderer, and kramdown + pick-your-xml2rfc-to-XXX-converter would be used to produce text/standard-html-version-of-an-RFC/PDF/whatever?

well, it's most true. There is some meta data and some special markup that github do not understand, but they tolerate it just fine.

**Comment by mcr** [comment]
@guyharris if there are no further issues, I guess I can now merge my own code, or you can push the button.

**Comment by guyharris** [comment]
So is there a reason why the links to run the current XML file for the pcapng draft through the xml2rfc site were removed, to preview what we currently have?

**Comment by mcr** [comment]
> So is there a reason why the links to run the current XML file for the pcapng draft through the xml2rfc site were removed, to preview what we currently have?

I just rebased the README, and tried to merge things sanely. I was trying to prefer the process that the MT Makefiles prefer (which is not, btw, the way I do things, but, I'm trying to hold my nose and go with majority rule).  I don't have a huge preference.

**Comment by guyharris** [comment]
> > So is there a reason why the links to run the current XML file for the pcapng draft through the xml2rfc site were removed, to preview what we currently have?
> 
> I just rebased the README, and tried to merge things sanely. I was trying to prefer the process that the MT Makefiles prefer (which is not, btw, the way I do things, but, I'm trying to hold my nose and go with majority rule). I don't have a huge preference.

OK, I put the links back; they seem to work.  They completely bypass the Makefile, just letting the IETF's xml2rfc server do the work.  That might require some further tweaking if and when we go to Markdown for the source, but, for now, let's continue to have the "show me the current draft in HTML/text/PDF" links work.

The "Editor's copy" link you added gets a 404.  The "Individual draft" link goes to, I guess, the last version that was ever provided to the IETF.

**Comment by mcr** [comment]
Guy Harris <notifications@github.com> wrote:
    > The "Editor's copy" link you added gets a 404.  The "Individual draft"
    > link goes to, I guess, the last version that was ever provided to the
    > IETF.

Yes, it requires some additional github and travis-ci setup, which I have not done yet.
I don't always do it, sometimes I just generate the files and commit them,
but that's a bit like commiting .o files.

**Pull request merged**
