### PR TITLE
Fix some more errors, nits, and xml2rfc warning

### PR DESCRIPTION
**Pull request by hadrielk**
See commit message.

### CODE REVIEW

**Comment by alagoutte** [comment]
Hi Hadriel,

You don't need to make a PR (Pull Request) from each change..
You can directly push a branch on one PR and if you need to update, you need only to edit your branch (and the PR will be update too)

i will look your change after (my first time to mark review on Github...)

**Comment by hadrielk** [comment]
I did it that way so you could choose not to pull/merge any specific change commit. (could you selectively choose if they were one pull request?)

**Comment by alagoutte** [comment]
You need to make a branch by commit (but may be commit are related ?)

**Comment by hadrielk** [comment]
I did do a branch for each commit - but they were a chain of branches - i.e., one was branched off of master, the second was branched off of the first, and the third was branched off the second. That way I could see the changes my previous commits had done. I do that frequently in wireshark changes. But I hadn't tried that before on github.

**Comment by packetfoo** [comment]
Hm how do I work on this, too? I have no GIT skills yet :-)

**Comment by hadrielk** [comment]
I think with the Github GUI apps you don't really need to know Git - though I could be wrong because I use normal git. But you can try out the GUI apps: for Windows use https://windows.github.com, and for Mac use https://mac.github.com.  You'll need to create a Github account, which you can do inside those GUI apps or on the website; then you'll need to fork this pcapng repository, which I think you can also do from within the apps (although it's trivial to do from Github's web interface instead).

**Comment by hadrielk** [comment]
Alexis: are you able to merge these, or do I need to re-do the pull request as one branch?

**Comment by alagoutte** [comment]
I have no yet looking your patch...

**Comment by hadrielk** [comment]
ping

**Comment by alagoutte** [comment]
Sorry.. i will try to look this week !

**Comment by alagoutte** [comment]
No warning for me also with this change ! 

Thanks

**Pull request merged**
