### PR TITLE
Replace multiple blank lines with a single blank line

### PR DESCRIPTION
**Pull request by fxlb**

### CODE REVIEW

**Comment by guyharris** [comment]
@mcr, are the DTD and XSLT files just taken from something the IETF has?

**Comment by fxlb** [comment]
The DTD  date is "2004-04-04".
This one has a date of "2009-10-06" (https://github.com/reschke/xml2rfc/blob/master/rfc2629.dtd)
Is there an official version ?

**Comment by fxlb** [comment]
The XSLT date is :
Copyright (c) 2006-2007, Julian Reschke (julian.reschke@greenbytes.de)
This is a more recent here : https://github.com/reschke/xml2rfc/blob/master/rfc2629.xslt
Copyright (c) 2006-2020, Julian Reschke (julian.reschke@greenbytes.de)

**Comment by mcr** [comment]
I object.
Blank lines in the source might represent pauses in thought or places where writers wanted to distance things in order to think better.
The DTD and XSLT files should not be touched (although they probably are not needed, period).
This just seems like busy work to me.

**Comment by fxlb** [comment]
Updated without DTD and XSLT.
You can close it if you prefer.

**Pull request merged**
