### PR TITLE
Remove old XML file

### PR DESCRIPTION
**Pull request by hadrielk**
Remove the old PCAP-DumpFileFormat.xml.

### CODE REVIEW

**Comment by guyharris** [comment]
Hmm.

Another possibility would be to take all of the commits of the *new* XML file, including the initial commit, turn them into commits to the old file (if that can be done in a way that not only preserves the committer, which Git supports, but also preserves the date and time of the commit), remove the old file, and then rename the old file to the new one, so that we can preserve the entire history.

**Comment by hadrielk** [comment]
Maybe 'git merge-file' would do it... I'll try

**Comment by hadrielk** [comment]
Actually the draft-tuexen one already had the history of the PCAP-dump one. If you run "git log --follow -p -- draft-tuexen-opsawg-pcapng.xml" on the branch with the PCAP-dump file deleted, git will show the history all the way back to, and including, the PCAP-dump file's history.

**Comment by guyharris** [comment]
I think the trick there is `--follow` - that might make `git log` decide that the last version of PCAP-DumpFileFormat.xml and the first version of draft-tuexen-opsawg-pcapng.xml are the same file, as they're similar enough to each other.

**Pull request merged**
